# Generated by Django 5.2.15 on 2026-06-17 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTransferIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('destination_hint', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='High', max_length=20)),
                ('reason', models.TextField(default='Abnormal number of file events in a short time window')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('moved', 'Moved'), ('manual_scan', 'Manual Scan'), ('bulk_transfer', 'Bulk Transfer')], max_length=30)),
                ('source_path', models.TextField(blank=True)),
                ('destination_path', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('process_name', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('sensitivity_category', models.CharField(blank=True, default='Normal', max_length=120)),
                ('classification_reason', models.TextField(blank=True)),
                ('is_authorized', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], db_index=True, default='Info', max_length=20)),
                ('risk_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('reason', models.TextField(default='Normal monitored event')),
                ('hash_before', models.CharField(blank=True, max_length=128)),
                ('hash_after', models.CharField(blank=True, max_length=128)),
                ('integrity_status', models.CharField(default='Not checked', max_length=120)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_extension', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IntegrityBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('hash_value', models.CharField(max_length=128)),
                ('algorithm', models.CharField(default='sha256', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='IntegrityCheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(db_index=True)),
                ('baseline_hash', models.CharField(blank=True, max_length=128)),
                ('current_hash', models.CharField(blank=True, max_length=128)),
                ('algorithm', models.CharField(default='sha256', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('Baseline Created', 'Baseline Created'), ('Unchanged', 'Unchanged'), ('Hash Mismatch', 'Hash Mismatch'), ('Missing', 'Missing'), ('Unreadable', 'Unreadable')], db_index=True, default='Unchanged', max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Integrity check history',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My File Transfer Monitoring Policy', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('monitored_directories', models.TextField(blank=True, default='', help_text='One real folder path per line. These folders are watched recursively by the monitor command.')),
                ('sensitive_directories', models.TextField(blank=True, default='', help_text='One real folder path per line. Files inside these folders are treated as sensitive.')),
                ('allowed_destinations', models.TextField(blank=True, default='', help_text='One real folder path per line. Sensitive files moved here are considered approved.')),
                ('restricted_files', models.TextField(blank=True, default='', help_text='Optional. One exact filename per line, for example payroll.xlsx or client_data.csv.')),
                ('sensitive_filename_keywords', models.TextField(blank=True, default='', help_text='Optional. One keyword per line, for example salary, passport, confidential, client, contract.')),
                ('sensitive_extensions', models.TextField(blank=True, default='', help_text='Optional. One extension per line, for example .xlsx, .csv, .pdf, .sql, .zip.')),
                ('blocked_destination_keywords', models.TextField(blank=True, default='', help_text='Optional. One destination keyword per line, for example USB, OneDrive, Dropbox, External, NetworkShare.')),
                ('trusted_process_keywords', models.TextField(blank=True, default='', help_text='Optional. Process keywords that reduce risk, for example backup or antivirus.')),
                ('hash_algorithm', models.CharField(choices=[('sha256', 'SHA256'), ('md5', 'MD5')], default='sha256', max_length=20)),
                ('burst_threshold_file_count', models.PositiveIntegerField(default=20)),
                ('burst_threshold_seconds', models.PositiveIntegerField(default=60)),
                ('email_alert_min_severity', models.CharField(choices=[('High', 'High and Critical'), ('Critical', 'Critical only'), ('Disabled', 'Disabled')], default='High', max_length=20)),
                ('simulated_email_recipients', models.TextField(blank=True, default='', help_text='Optional. One recipient per line. Email evidence is simulated and stored locally in SQLite.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Monitoring policies',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('closed', 'Closed'), ('false_positive', 'False Positive')], db_index=True, default='open', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('analyst_notes', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='monitor.fileevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fileevent',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.monitoringpolicy'),
        ),
        migrations.CreateModel(
            name='SimulatedEmailAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('delivery_status', models.CharField(default='Simulated - Stored Locally', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='monitor.alert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
