# Generated by Django 5.2.15 on 2026-06-17 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringpolicy',
            options={'ordering': ['-is_active', 'name'], 'verbose_name_plural': 'Monitoring policies'},
        ),
        migrations.AddField(
            model_name='alert',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='escalation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='escalation_recipients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='initial_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulktransferincident',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.monitoringpolicy'),
        ),
        migrations.AddField(
            model_name='monitoringpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoringpolicy',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monitoringpolicy',
            name='escalation_after_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='monitoringpolicy',
            name='escalation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoringpolicy',
            name='escalation_group_recipients',
            field=models.TextField(blank=True, default='', help_text='One group email per line. Used when no assigned admin/analyst claims an alert in time.'),
        ),
        migrations.AddField(
            model_name='monitoringpolicy',
            name='notify_policy_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulatedemailalert',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulatedemailalert',
            name='purpose',
            field=models.CharField(choices=[('alert', 'Initial Alert Notification'), ('escalation', 'Escalation Notification'), ('otp', 'Password Reset OTP'), ('system', 'System Email')], default='alert', max_length=30),
        ),
        migrations.AlterField(
            model_name='monitoringpolicy',
            name='simulated_email_recipients',
            field=models.TextField(blank=True, default='', help_text='Optional. One recipient per line for direct alert notifications.'),
        ),
        migrations.AlterField(
            model_name='simulatedemailalert',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='monitor.alert'),
        ),
        migrations.AlterField(
            model_name='simulatedemailalert',
            name='delivery_status',
            field=models.CharField(default='Stored Locally', max_length=80),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('away', 'Away'), ('off_duty', 'Off Duty'), ('on_leave', 'On Leave')], default='available', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sftm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='PolicyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('policy_admin', 'Policy Admin'), ('analyst', 'Security Analyst'), ('auditor', 'Read-only Auditor')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_policy_memberships', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='monitor.monitoringpolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['policy__name', 'role', 'user__username'],
                'unique_together': {('policy', 'user', 'role')},
            },
        ),
    ]
