# Generated by Django 5.2.15 on 2026-06-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_monitoringpolicy_options_alert_assigned_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('copied', 'Copied'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('moved', 'Moved'), ('manual_scan', 'Manual Scan'), ('bulk_transfer', 'Bulk Transfer')], max_length=30),
        ),
    ]
